<?php

namespace AppBundle\Repository;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveInstanceCount()
    {
        $qb = $this->createQueryBuilder('entity');

        $result = $qb->select($qb->expr()->count('entity.id'))
            ->where($qb->expr()->eq('entity.status', $qb->expr()->literal('active')))
            ->getQuery()->getSingleScalarResult();

        return $result;
    }

    public function getSuspendedInstanceCount()
    {
        $qb = $this->createQueryBuilder('entity');

        $result = $qb->select($qb->expr()->count('entity.id'))
            ->where($qb->expr()->eq('entity.status', $qb->expr()->literal('suspended')))
            ->getQuery()->getSingleScalarResult();

        return $result;
    }

    public function search($query)
    {
        $qb = $this->createQueryBuilder('entity');

        $result = $qb
            ->where($qb->expr()->like('entity.name', $qb->expr()->literal('%'.$query.'%')))
            ->getQuery()->getResult();

        return $result;
    }
}
